using UnityEngine;
using System;

public class MusicManager : MonoBehaviour
{
    public AudioSource audioSource; // La fuente de audio que contiene la canci칩n
    public float[] spectrumData = new float[256]; // Tama침o del array para el an치lisis FFT
    public event Action<float> OnHighDetected; // Evento para bajos pronunciados
    public event Action<float> OnLowDetected; // Evento para altos pronunciados

    [Range(0.01f, 0.5f)] public float sensitivity = 0.1f; // Sensibilidad para detectar picos
    [Range(0.01f, 0.1f)] [SerializeField] private float lowThreshold; // Umbral para detectar bajos
    [Range(0.25f, 0.35f)] [SerializeField] private float highThreshold; // Umbral para detectar altos
    
    void Update()
    {
        // An치lisis FFT
        audioSource.GetSpectrumData(spectrumData, 0, FFTWindow.BlackmanHarris);
        
        float lowSum = 0f;
        float highSum = 0f;
        
        // Sumamos las frecuencias bajas y altas
        for (int i = 0; i < spectrumData.Length / 2; i++) 
        {
            lowSum += spectrumData[i]; // Frecuencias bajas
        }
        
        for (int i = spectrumData.Length / 2; i < spectrumData.Length; i++) 
        {
            highSum += spectrumData[i]; // Frecuencias altas
        }

        // Si las frecuencias bajas y altas sobrepasan ciertos umbrales, emitimos eventos
        if (lowSum > lowThreshold) 
        {
            OnLowDetected?.Invoke(lowSum);
        }

        if (highSum > highThreshold) 
        {
            OnHighDetected?.Invoke(highSum);
        }
    }
}
